version: '3.5'
services:
  nginx:
    image: nginx:1.16
    ports:
      - 8080:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./index.sh:/var/www/html/cgi-bin/index.sh
    depends_on:
      - fcgiwrap

  fcgiwrap:
    image: davidalger/fcgiwrap
    volumes:
      - ./index.sh:/var/www/html/cgi-bin/index.sh
